# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mouse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mouse.proto',
  package='mouseSenderPackage',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bmouse.proto\x12\x12mouseSenderPackage\"!\n\x0b\x45ventString\x12\x12\n\nmouseevent\x18\x01 \x01(\t2`\n\x0bMouseSender\x12Q\n\x0bmouseStream\x12\x1f.mouseSenderPackage.EventString\x1a\x1f.mouseSenderPackage.EventString0\x01\x62\x06proto3'
)




_EVENTSTRING = _descriptor.Descriptor(
  name='EventString',
  full_name='mouseSenderPackage.EventString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mouseevent', full_name='mouseSenderPackage.EventString.mouseevent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['EventString'] = _EVENTSTRING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventString = _reflection.GeneratedProtocolMessageType('EventString', (_message.Message,), {
  'DESCRIPTOR' : _EVENTSTRING,
  '__module__' : 'mouse_pb2'
  # @@protoc_insertion_point(class_scope:mouseSenderPackage.EventString)
  })
_sym_db.RegisterMessage(EventString)



_MOUSESENDER = _descriptor.ServiceDescriptor(
  name='MouseSender',
  full_name='mouseSenderPackage.MouseSender',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=70,
  serialized_end=166,
  methods=[
  _descriptor.MethodDescriptor(
    name='mouseStream',
    full_name='mouseSenderPackage.MouseSender.mouseStream',
    index=0,
    containing_service=None,
    input_type=_EVENTSTRING,
    output_type=_EVENTSTRING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MOUSESENDER)

DESCRIPTOR.services_by_name['MouseSender'] = _MOUSESENDER

# @@protoc_insertion_point(module_scope)
